@startuml emp
class Employee {
  - employeeId: int
  - name: string
  # salary: double
  + Employee(employeeId: int, name: string)
  + getEmployeeId(): int
  + getName(): string
  + getSalary(): double
  + increaseSalary(amount: double)
  - calculateBonus(): double
}
@enduml
